theme: jekyll-theme-architect
title: Docker UI
description: "Project documentation for Docker UI"
markdown: kramdown
kramdown:
  input: GFM
github:
  private: false
  license:
    name: MIT
  repository_url: "https://github.com/raz-m12/raz-m12.github.io"
